import { IPhrase } from './types';

const funPhrases = [
  { category: 'Movies', value: 'Super Troopers' },
  { category: 'Fictional Characters', value: 'Pikachu' },
  { category: 'Cartoons', value: 'SpongeBob SquarePants' },
  { category: 'Video Games', value: 'Mario Kart' },
  { category: 'Comedy', value: 'Knock, Knock Jokes' },
  { category: 'Board Games', value: 'Monopoly' },
  { category: 'Pop Culture', value: 'Dabbing Unicorn' },
  { category: 'Sports', value: 'Bungee Jumping' },
  { category: 'Food', value: 'Pizza Party' },
  { category: 'Animals', value: 'Sloth Life' },
  { category: 'Music', value: 'Ukulele Serenade' },
  { category: 'Fantasy', value: 'Dragon Slaying' },
  { category: 'Travel', value: 'Hot Air Balloon Ride' },
  { category: 'Space', value: 'Intergalactic Disco' },
  { category: 'Inventions', value: 'Flying Car' },
  { category: 'Dance', value: 'Breakdancing' },
  { category: 'Fashion', value: 'Funky Socks' },
  { category: 'Science Fiction', value: 'Robot Rebellion' },
  { category: 'Gardening', value: 'Talking Plants' },
  { category: 'Fitness', value: 'Zumba Party' },
  { category: 'Technology', value: 'Robot Companions' },
  { category: 'Weather', value: 'Rainbow Chasing' },
  { category: 'Adventure', value: 'Treasure Hunt' },
  { category: 'Holidays', value: 'Candy Cane Lane' },
  { category: 'Superheroes', value: 'Captain Marvel' },
  { category: 'Fairy Tales', value: 'Enchanted Castle' },
  { category: 'Sports', value: 'Sumo Wrestling' },
  { category: 'Cuisine', value: 'Sushi Delight' },
  { category: 'Animals', value: 'Penguin Parade' },
  { category: 'Music', value: 'Jazz Hands' },
  { category: 'Movies', value: 'The Princess Bride' },
  { category: 'Board Games', value: 'Candy Land' },
  { category: 'Pop Culture', value: 'Meme Magic' },
  { category: 'Comedy', value: 'Tickle Monster' },
  { category: 'Video Games', value: 'Pokémon Go' },
  { category: 'Cartoons', value: 'Adventure Time' },
  { category: 'Space', value: 'Alien Abduction' },
  { category: 'Fantasy', value: 'Unicorn Dreams' },
  { category: 'Dance', value: 'Disco Fever' },
  { category: 'Fashion', value: 'Tutu Trend' },
  { category: 'Science Fiction', value: 'Time Travelers' },
  { category: 'Gardening', value: 'Dancing Flowers' },
  { category: 'Fitness', value: 'Zombie Run' },
  { category: 'Technology', value: 'Virtual Reality Party' },
  { category: 'Weather', value: 'Sunshine Bliss' },
  { category: 'Adventure', value: 'Pirate Treasure' },
  { category: 'Holidays', value: 'Elf Workshop' },
  { category: 'Superheroes', value: 'Wonder Woman' },
  { category: 'Fairy Tales', value: 'Magic Beanstalk' },
  { category: 'Movies', value: 'Back to the Future' },
  { category: 'Video Games', value: 'Fortnite Dance' },
  { category: 'Fictional Characters', value: 'Yoda' },
  { category: 'Sports', value: 'Slam Dunk' },
  { category: 'Food', value: 'Pineapple Pizza' },
  { category: 'Cartoons', value: 'Scooby-Doo Mystery' },
  { category: 'Music', value: "Rock 'n' Roll" },
  { category: 'Science', value: 'Mad Scientist' },
  { category: 'Travel', value: 'Road Trip Playlist' },
  { category: 'Animals', value: 'Party Parrot' },
  { category: 'Fashion', value: 'Polka Dot Trend' },
  { category: 'Technology', value: 'Selfie Stick' },
  { category: 'Weather', value: 'Rainbow Connection' },
  { category: 'Hobbies', value: 'Comic Book Collecting' },
  { category: 'Board Games', value: 'Pictionary Champ' },
  { category: 'Pop Culture', value: 'TikTok Craze' },
  { category: 'Comedy', value: 'Stand-up Special' },
  { category: 'History', value: 'Ancient Aliens Theory' },
  { category: 'Fantasy', value: 'Wizard Academy' },
  { category: 'Space', value: 'Moonwalk Party' },
  { category: 'Science Fiction', value: 'Time-Traveling Tardis' },
  { category: 'Nature', value: 'Whimsical Wonderland' },
  { category: 'Art', value: 'Abstract Doodle' },
  { category: 'Superheroes', value: 'Invisible Cloak' },
  { category: 'Cuisine', value: 'Gourmet Cupcakes' },
  { category: 'Memes', value: 'Distracted Boyfriend' },
  { category: 'Fitness', value: 'Zumba Marathon' },
  { category: 'Literature', value: 'Sherlock Holmes Mystery' },
  { category: 'Vehicles', value: 'Hoverboard Adventure' },
  { category: 'Gaming', value: 'Mario Party Madness' },
  { category: 'Inventions', value: 'Flying Saucer' },
  { category: 'Social Media', value: 'Emoji Expressions' },
  { category: 'Entertainment', value: 'Circus Spectacle' },
  { category: 'DIY Projects', value: 'Paper Airplane Fleet' },
  { category: 'Wild West', value: 'Cowboy Rodeo' },
  { category: 'Dance', value: 'Breakdance Battle' },
  { category: 'Fairy Tales', value: 'Pixie Dust Adventure' },
  { category: 'Adventure', value: 'Lost Treasure Map' },
  { category: 'Mystery', value: 'Whodunit Puzzle' },
  { category: 'World Records', value: 'Human Dominoes' },
  { category: 'Outer Space', value: 'Interstellar Vacation' },
  { category: 'Under the Sea', value: 'Mermaid Lagoon' },
  { category: 'Carnival Fun', value: 'Cotton Candy Bliss' },
  { category: 'Spy Games', value: 'Secret Agent Mission' },
  { category: 'Fashion Trends', value: 'Tie-Dye Revolution' },
  { category: 'Sci-Fi Robots', value: 'Robo-Dance Party' },
  { category: 'Fairytale Creatures', value: 'Dragon Carnival' },
  { category: 'Baking Delights', value: 'Cupcake Wonderland' },
  { category: 'Exotic Animals', value: 'Safari Safari' },
  { category: 'Ocean Adventures', value: 'Deep Sea Diving' },
  { category: 'Mythical Beasts', value: 'Phoenix Rising' },
  { category: 'Magical Moments', value: "Wizard's Duel" },
  { category: 'Tech Marvels', value: 'Virtual Reality Escapade' },
  { category: 'Comic Book Heroes', value: 'Superpower Showdown' },
  { category: 'Music Festivals', value: 'Jam Session Extravaganza' },
];

const movieQuotes = [
  { category: 'Movie Quotes', value: 'May the Force be with you' },
  { category: 'Famous Quotes', value: "I'm an idiot sandwich" },
];

const danceMoves = [
  { category: 'Dance Move', value: 'Crank that soulja boy' },
  { category: 'Dance Move', value: 'Hit the Quan' },
  { category: 'Dance Move', value: 'Teach Me How to Dougie' },
  { category: 'Dance Move', value: 'Chicken Noodle Soup' },
  { category: 'Dance Move', value: 'Pop Lock & Drop It' },
];

const whereAreWeGoing = [
  { category: 'Where are we going', value: 'KAYAKING & SWIMMING' },
  { category: 'Where are we going', value: 'HIKING THROUGH THE RAINFOREST' },
  { category: 'Where are we going', value: 'JOGGING DOWN THE BLOCK' },
  {
    category: 'Where are we going',
    value: 'GATHERING SEASHELLS ON THE SEA SHORE',
  },
];

const classicMovieTitles = [
  { category: 'Classic Movie', value: 'The Godfather' },
  { category: 'Classic Movie', value: 'The Nightmare Before Christmas' },
  { category: 'Classic Movie', value: 'A Beautiful Mind' },
  { category: 'Classic Movie', value: 'The Parent Trap' },
  { category: 'Classic Movie', value: 'The Color Purple' },
  { category: 'Classic Movie', value: 'The Wizard of Oz' },
  { category: 'Classic Movie', value: 'The Silence of the Lambs' },
  { category: 'Classic Movie', value: 'WILLY WONKA AND THE CHOCOLATE FACTORY' },
];

export const phrases: IPhrase[] = [
  ...funPhrases,
  ...movieQuotes,
  ...danceMoves,
  ...whereAreWeGoing,
  ...classicMovieTitles,
];
